### ISSUE TITLE
Sentencizer

### ISSUE THREAD

**Issue by beperron** [beperron/COVID-research#4]
I am in need of the sentencizer using `spacy`.  Here is a video description of the target output.  Please create a Gist in GitHub for this procedure.  Please include the placeholders where the code can be easily changed for somebody to resuse.  

https://drive.google.com/file/d/16AwDXjg3UIwXDRyBlPnNa7aMc4rQN-b1/view

[sentencizer.xlsx](https://github.com/beperron/COVID-research/files/7130249/sentencizer.xlsx)

**Comment by Soul-Jacker** [comment]
https://gist.github.com/Soul-Jacker/79efcd50c4215207cc1c1646afd6ce21
