### ISSUE TITLE
English detection 

### ISSUE THREAD

**Issue by beperron** [beperron/COVID-research#5]
Please use `spacy` to build a language detector.  Look at the `spacy` page first and then the GitHub site.  Please create the detector to loop through a series of texts like the one attached.  You should add some other languages in the data sheet to process, but this is the typical problem I want to solve.  Ideally, the function would produce two different variables:  English (True/False) or Language (i.e., the language detected).  Please make this as a Gist in GitHub  

[example.csv](https://github.com/beperron/COVID-research/files/7130284/example.csv)

https://spacy.io/universe/project/spacy-langdetect
https://github.com/Abhijit-2592/spacy-langdetect

**Comment by Soul-Jacker** [comment]
[Here is the gist you can use. ](https://gist.github.com/Soul-Jacker/7dcbe9b328da31117361de16b978ba3b)
